In [25]:
import pandas as pd
import numpy as np

In [26]:
dfTeste = pd.read_csv('./baseDeDados/test.csv') # base que usaremos pra testar o modelo e submeter no kaggle
category = pd.read_csv('./baseDeDados/category.csv') # única informação a mais que tem é o nome da categoria em inglês, irrelevante
customers = pd.read_csv('./baseDeDados/customers.csv') # puxa todas as infos
order_items = pd.read_csv('./baseDeDados/order_itens.csv') # puxa todas as infos
order_payments = pd.read_csv('./baseDeDados/order_payments.csv') # puxa todas as infos
order_reviews = pd.read_csv('./baseDeDados/order_reviews.csv') # não puxa nada, pq o review só tem depois que o produto é entregue
orders = pd.read_csv('./baseDeDados/orders.csv') # não puxa nada, pq só tem infos de vendas que já foram entregues
products = pd.read_csv('./baseDeDados/products.csv') # puxa todas as infos
sellers = pd.read_csv('./baseDeDados/sellers.csv') # puxa todas as infos

In [27]:
dfTeste

,order_id,customer_id,order_purchase_timestamp,order_approved_at
0,cee3292f46ede6ea1dfabfcb200fcf47,0f8feee05f830b2be5955cf674a7d8f1,6/21/2018 15:00,6/21/2018 17:18
1,50dca53ca33b739bef09e7933e8b380e,d0580aed7f303a707d93b00b84c591a7,7/14/2018 09:47,7/14/2018 10:04
2,8087ec71e393d4dc6fc48041fe63cd51,b8dfb418e6cad762b91febf827d4b2e5,5/14/2018 10:03,5/14/2018 10:15
3,e6b6557ce111de79b31cc857f20ba212,90c8fe0d707ea62be3fcb5abd7bc784f,5/22/2018 18:41,5/22/2018 18:57
4,0b09c5e4c2512f627190ac55a78c35a3,6ba83000cf8c24413916a7a72fcb5173,4/30/2018 19:31,5/3/2018 04:12
...,...,...,...,...
28147,81cedc4d2132eb6f512354166e51b187,a8f6bb35d78515a1762eb626d52b6352,7/30/2018 21:02,7/30/2018 21:10
28148,95811675a89b66659996da5285a021db,5885969ba920706beb8d5381a2ba981c,8/9/2018 11:07,8/9/2018 15:25
28149,25bd2ad9d282f59e4e6a048ef9bf214f,be34bf56044c5614fc66d97251c0adc6,3/12/2018 16:20,3/12/2018 17:09
28150,9f9ac312604229686c04260955495c70,3357c4c3ecf82709236158cb2ac0ce9b,5/24/2018 11:38,5/24/2018 11:53
28151,f51c9940410ef77422e4efbca407c161,ceeaae7ee13b40a086d0140281bef2ac,8/16/2018 11:05,8/17/2018 03:30

In [28]:
dfTeste = pd.merge(dfTeste, customers, on=['customer_id', 'customer_id'], how='left')
dfTeste = pd.merge(dfTeste, order_items, on=['order_id', 'order_id'], how='left')
dfTeste = pd.merge(dfTeste, order_payments, on=['order_id', 'order_id'], how='left')
dfTeste = pd.merge(dfTeste, products, on=['product_id', 'product_id'], how='left')
dfTeste = pd.merge(dfTeste, sellers, on=['seller_id', 'seller_id'], how='left')

pd.set_option('display.max_columns', None)
dfTeste

,order_id,customer_id,order_purchase_timestamp,order_approved_at,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,payment_sequential,payment_type,payment_installments,payment_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state
0,cee3292f46ede6ea1dfabfcb200fcf47,0f8feee05f830b2be5955cf674a7d8f1,6/21/2018 15:00,6/21/2018 17:18,04d1643d1bf6c54f0b099c708e623466,8280,NaN,NaN,1,1bfb290d7273a442c874dbe74b4abae6,7c67e1448b00f6e969d365cea6b010ab,2018-07-05 17:18:41.000,69.99,23.20,1,boleto,1,186.38,moveis_escritorio,19.0,883.0,1.0,10075.0,55.0,64.0,26.0,8577,itaquaquecetuba,SP
1,cee3292f46ede6ea1dfabfcb200fcf47,0f8feee05f830b2be5955cf674a7d8f1,6/21/2018 15:00,6/21/2018 17:18,04d1643d1bf6c54f0b099c708e623466,8280,NaN,NaN,2,1bfb290d7273a442c874dbe74b4abae6,7c67e1448b00f6e969d365cea6b010ab,2018-07-05 17:18:41.000,69.99,23.20,1,boleto,1,186.38,moveis_escritorio,19.0,883.0,1.0,10075.0,55.0,64.0,26.0,8577,itaquaquecetuba,SP
2,50dca53ca33b739bef09e7933e8b380e,d0580aed7f303a707d93b00b84c591a7,7/14/2018 09:47,7/14/2018 10:04,83f6b0c43f9281884da6fb400b587207,7151,guarulhos,sao paulo,1,eb048e296b8db6cd64b1bafd9500786c,1900267e848ceeba8fa32d80c1a5f5a8,2018-07-17 10:04:14.000,19.90,12.80,1,credit_card,3,65.40,cama_mesa_banho,52.0,149.0,1.0,250.0,16.0,10.0,16.0,14940,ibitinga,SP
3,50dca53ca33b739bef09e7933e8b380e,d0580aed7f303a707d93b00b84c591a7,7/14/2018 09:47,7/14/2018 10:04,83f6b0c43f9281884da6fb400b587207,7151,guarulhos,sao paulo,2,113f80f12c8892f0c59206f70b862b40,1900267e848ceeba8fa32d80c1a5f5a8,2018-07-17 10:04:14.000,19.90,12.80,1,credit_card,3,65.40,cama_mesa_banho,52.0,170.0,1.0,250.0,16.0,10.0,16.0,14940,ibitinga,SP
4,8087ec71e393d4dc6fc48041fe63cd51,b8dfb418e6cad762b91febf827d4b2e5,5/14/2018 10:03,5/14/2018 10:15,ae85516c85361785d9151930418af0cb,4013,SAO PAULO,SP,1,39cdb64dad488a6037d828d1cd514255,8f119a0aee85c0c8fc534629734e94fd,2018-05-18 10:15:20.000,22.50,8.64,1,credit_card,3,179.68,casa_construcao,60.0,890.0,2.0,300.0,28.0,9.0,18.0,6440,barueri,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33261,25bd2ad9d282f59e4e6a048ef9bf214f,be34bf56044c5614fc66d97251c0adc6,3/12/2018 16:20,3/12/2018 17:09,768e9ed92dd4fe880672c8e90dc4f74c,66610,belem,PA,1,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-03-16 17:09:53.000,53.90,42.44,1,credit_card,2,289.02,ferramentas_jardim,57.0,366.0,2.0,1650.0,30.0,22.0,30.0,15025,sao jose do rio preto,SP
33262,25bd2ad9d282f59e4e6a048ef9bf214f,be34bf56044c5614fc66d97251c0adc6,3/12/2018 16:20,3/12/2018 17:09,768e9ed92dd4fe880672c8e90dc4f74c,66610,belem,PA,2,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-03-16 17:09:53.000,53.90,42.44,1,credit_card,2,289.02,ferramentas_jardim,57.0,366.0,2.0,1650.0,30.0,22.0,30.0,15025,sao jose do rio preto,SP
33263,25bd2ad9d282f59e4e6a048ef9bf214f,be34bf56044c5614fc66d97251c0adc6,3/12/2018 16:20,3/12/2018 17:09,768e9ed92dd4fe880672c8e90dc4f74c,66610,belem,PA,3,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-03-16 17:09:53.000,53.90,42.44,1,credit_card,2,289.02,ferramentas_jardim,57.0,366.0,2.0,1650.0,30.0,22.0,30.0,15025,sao jose do rio preto,SP
33264,9f9ac312604229686c04260955495c70,3357c4c3ecf82709236158cb2ac0ce9b,5/24/2018 11:38,5/24/2018 11:53,bc13219ef5b1a254d34e3e6112303dfd,3315,NaN,NaN,1,bb50f2e236e5eea0100680137654686c,f7ba60f8c3f99e7ee4042fdef03b70c4,2018-05-28 11:53:34.000,330.00,10.07,1,credit_card,8,340.07,beleza_saude,60.0,2644.0,6.0,400.0,34.0,4.0,22.0,9628,sao bernardo do campo,SP
33265,f51c9940410ef77422e4efbca407c161,ceeaae7ee13b40a086d0140281bef2ac,8/16/2018 11:05,8/17/2018 03:30,d9f2c7c53b2b8071bc518513a8c7a735,85301,laranjeiras do sul,NaN,1,020a80cb704bf65f38761fcedf2af192,ef2fbc2b607d8492bcffe657a4645434,2018-08-22 03:30:17.000,49.90,19.54,1,boleto,1,69.44,automotivo,35.0,1512.0,3.0,800.0,26.0,9.0,24.0,20051,rio de janeiro,RJ

In [29]:
dfTeste.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33266 entries, 0 to 33265
Data columns (total 29 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   order_id                    33266 non-null  object
 1   customer_id                 33266 non-null  object
 2   order_purchase_timestamp    33266 non-null  object
 3   order_approved_at           33266 non-null  object
 4   customer_unique_id          33266 non-null  object
 5   customer_zip_code_prefix    33266 non-null  int64
 6   customer_city               21606 non-null  object
 7   customer_state              16604 non-null  object
 8   order_item_id               33266 non-null  int64
 9   product_id                  33266 non-null  object
 10  seller_id                   33266 non-null  object
 11  shipping_limit_date         33266 non-null  object
 12  price                       32964 non-null  float64
 13  freight_value               32945 non-null  float64
 14  payment_sequential          33266 non-null  int64
 15  payment_type                33266 non-null  object
 16  payment_installments        33266 non-null  int64
 17  payment_value               33266 non-null  float64
 18  product_category_name       33088 non-null  object
 19  product_name_lenght         33088 non-null  float64
 20  product_description_lenght  33088 non-null  float64
 21  product_photos_qty          33088 non-null  float64
 22  product_weight_g            33266 non-null  float64
 23  product_length_cm           33266 non-null  float64
 24  product_height_cm           33266 non-null  float64
 25  product_width_cm            33266 non-null  float64
 26  seller_zip_code_prefix      33266 non-null  int64
 27  seller_city                 33266 non-null  object
 28  seller_state                33266 non-null  object
dtypes: float64(10), int64(5), object(14)
memory usage: 7.4+ MB

In [30]:
# Deletando colunas e linhas duplicadas
dfTeste = dfTeste.T.drop_duplicates().T

In [31]:
# Importando a dataBase e imprimindo
dfCEP = pd.read_excel('./baseDeDados/listaCEP.xlsx')
dfCEP

,Estado,Localidade,Faixa de CEP,CEP Inicial,CEP Final,Situação,Tipo de Faixa
0,acre,acrelândia,69945-000 a 69949-999,69945,69950,Não codificada por logradouros,Total do município
1,acre,assis brasil,69935-000 a 69939-999,69935,69940,Não codificada por logradouros,Total do município
2,acre,brasiléia,69932-000 a 69933-999,69932,69934,Não codificada por logradouros,Total do município
3,acre,bujari,69926-000 a 69926-999,69926,69927,Não codificada por logradouros,Total do município
4,acre,capixaba,69931-000 a 69931-999,69931,69932,Não codificada por logradouros,Total do município
...,...,...,...,...,...,...,...
6010,tocantins,tocantinópolis,77900-000 a 77902-999,77900,77903,Não codificada por logradouros,Total do município
6011,tocantins,tupirama,77704-000 a 77707-999,77704,77708,Não codificada por logradouros,Total do município
6012,tocantins,tupiratins,77743-000 a 77744-999,77743,77745,Não codificada por logradouros,Total do município
6013,tocantins,wanderlândia,77860-000 a 77869-999,77860,77870,Não codificada por logradouros,Total do município
6014,tocantins,xambioá,77880-000 a 77884-999,77880,77885,Não codificada por logradouros,Total do município

In [32]:
# Transformando todos os estado para o nome completo

for i in range(0, len(dfTeste)):
    if str(dfTeste['customer_state'][i]) == "AC":
        dfTeste['customer_state'][i] = "acre"
    elif str(dfTeste['customer_state'][i]) == "AL":
        dfTeste['customer_state'][i] = "alagoas"
    elif str(dfTeste['customer_state'][i]) == "AP":
        dfTeste['customer_state'][i] = "amapa"
    elif str(dfTeste['customer_state'][i]) == "AM":
        dfTeste['customer_state'][i] = "amazonas"
    elif str(dfTeste['customer_state'][i]) == "BA":
        dfTeste['customer_state'][i] = "bahia"
    elif str(dfTeste['customer_state'][i]) == "CE":
        dfTeste['customer_state'][i] = "ceara"
    elif str(dfTeste['customer_state'][i]) == "ES":
        dfTeste['customer_state'][i] = "espirito santo"
    elif str(dfTeste['customer_state'][i]) == "GO":
        dfTeste['customer_state'][i] = "goias"
    elif str(dfTeste['customer_state'][i]) == "MA":
        dfTeste['customer_state'][i] = "maranhao"
    elif str(dfTeste['customer_state'][i]) == "MT":
        dfTeste['customer_state'][i] = "mato grosso"
    elif str(dfTeste['customer_state'][i]) == "MS":
        dfTeste['customer_state'][i] = "mato grosso do sul"
    elif str(dfTeste['customer_state'][i]) == "MG":
        dfTeste['customer_state'][i] = "minas gerais"
    elif str(dfTeste['customer_state'][i]) == "PA":
        dfTeste['customer_state'][i] = "para"
    elif str(dfTeste['customer_state'][i]) == "PB":
        dfTeste['customer_state'][i] = "paraiba"
    elif str(dfTeste['customer_state'][i]) == "PR":
        dfTeste['customer_state'][i] = "parana"
    elif str(dfTeste['customer_state'][i]) == "PE":
        dfTeste['customer_state'][i] = "pernambuco"
    elif str(dfTeste['customer_state'][i]) == "PI":
        dfTeste['customer_state'][i] = "piaui"
    elif str(dfTeste['customer_state'][i]) == "RJ":
        dfTeste['customer_state'][i] = "rio de janeiro"
    elif str(dfTeste['customer_state'][i]) == "RN":
        dfTeste['customer_state'][i] = "rio grande do norte"
    elif str(dfTeste['customer_state'][i]) == "RS":
        dfTeste['customer_state'][i] = "rio grande do sul"
    elif str(dfTeste['customer_state'][i]) == "RO":
        dfTeste['customer_state'][i] = "rondonia"
    elif str(dfTeste['customer_state'][i]) == "RR":
        dfTeste['customer_state'][i] = "roraima"
    elif str(dfTeste['customer_state'][i]) == "SC":
        dfTeste['customer_state'][i] = "santa catarina"
    elif str(dfTeste['customer_state'][i]) == "SP":
        dfTeste['customer_state'][i] = "sao paulo"
    elif str(dfTeste['customer_state'][i]) == "SE":
        dfTeste['customer_state'][i] = "sergipe"
    elif str(dfTeste['customer_state'][i]) == "TO":
        dfTeste['customer_state'][i] = "tocantins"
    elif str(dfTeste['customer_state'][i]) == "DF":
        dfTeste['customer_state'][i] = "distrito federal"

C:\Users\leopa\AppData\Local\Temp\ipykernel_15424\2118495776.py:51: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfTeste['customer_state'][i] = "sao paulo"
C:\Users\leopa\AppData\Local\Temp\ipykernel_15424\2118495776.py:27: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfTeste['customer_state'][i] = "minas gerais"
C:\Users\leopa\AppData\Local\Temp\ipykernel_15424\2118495776.py:49: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfTeste['customer_state'][i] = "santa catarina"
C:\Users\leopa\AppData\Local\Temp\ipykernel_15424\2118495776.py:33: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfTeste['customer_state'][i] = "parana"
C:\Users\leopa\AppData\Local\Temp\ipykernel_15424\2118495776.py:57: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfTeste['customer_state'][i] = "distrito federal"
C:\Users\leopa\AppData\Local\Temp\ipykernel_15424\2118495776.py:39: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfTeste['customer_state'][i] = "rio de janeiro"
C:\Users\leopa\AppData\Local\Temp\ipykernel_15424\2118495776.py:43: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfTeste['customer_state'][i] = "rio grande do sul"
C:\Users\leopa\AppData\Local\Temp\ipykernel_15424\2118495776.py:17: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfTeste['customer_state'][i] = "espirito santo"
C:\Users\leopa\AppData\Local\Temp\ipykernel_15424\2118495776.py:23: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfTeste['customer_state'][i] = "mato grosso"
C:\Users\leopa\AppData\Local\Temp\ipykernel_15424\2118495776.py:35: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfTeste['customer_state'][i] = "pernambuco"
C:\Users\leopa\AppData\Local\Temp\ipykernel_15424\2118495776.py:53: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfTeste['customer_state'][i] = "sergipe"
C:\Users\leopa\AppData\Local\Temp\ipykernel_15424\2118495776.py:13: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfTeste['customer_state'][i] = "bahia"
C:\Users\leopa\AppData\Local\Temp\ipykernel_15424\2118495776.py:41: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfTeste['customer_state'][i] = "rio grande do norte"
C:\Users\leopa\AppData\Local\Temp\ipykernel_15424\2118495776.py:19: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfTeste['customer_state'][i] = "goias"
C:\Users\leopa\AppData\Local\Temp\ipykernel_15424\2118495776.py:21: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfTeste['customer_state'][i] = "maranhao"
C:\Users\leopa\AppData\Local\Temp\ipykernel_15424\2118495776.py:31: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfTeste['customer_state'][i] = "paraiba"
C:\Users\leopa\AppData\Local\Temp\ipykernel_15424\2118495776.py:37: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfTeste['customer_state'][i] = "piaui"
C:\Users\leopa\AppData\Local\Temp\ipykernel_15424\2118495776.py:15: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfTeste['customer_state'][i] = "ceara"
C:\Users\leopa\AppData\Local\Temp\ipykernel_15424\2118495776.py:11: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfTeste['customer_state'][i] = "amazonas"
C:\Users\leopa\AppData\Local\Temp\ipykernel_15424\2118495776.py:45: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfTeste['customer_state'][i] = "rondonia"
C:\Users\leopa\AppData\Local\Temp\ipykernel_15424\2118495776.py:7: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfTeste['customer_state'][i] = "alagoas"
C:\Users\leopa\AppData\Local\Temp\ipykernel_15424\2118495776.py:29: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.


In [33]:
# Completando a cidade e estado do comprador com base no zip code
for i in range(0, len(dfTeste)):
    if str(dfTeste['customer_city'][i]) == 'nan' or str(dfTeste['customer_state'][i]) == 'nan':
        for j in range(0, len(dfCEP)):
            if (dfTeste['customer_zip_code_prefix'][i] >= dfCEP['CEP Inicial'][j]) and (dfTeste['customer_zip_code_prefix'][i] <= dfCEP['CEP Final'][j]):
                dfTeste['customer_city'][i] = dfCEP['Localidade'][j]
                dfTeste['customer_state'][i] = dfCEP['Estado'][j]
                break

C:\Users\leopa\AppData\Local\Temp\ipykernel_15424\3701409745.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfTeste['customer_city'][i] = dfCEP['Localidade'][j]
C:\Users\leopa\AppData\Local\Temp\ipykernel_15424\3701409745.py:7: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfTeste['customer_state'][i] = dfCEP['Estado'][j]

In [34]:
# Colocando os estados e as cidades em letra minuscula
for i in range(0, len(dfTeste)):
    dfTeste['customer_city'][i] = str(dfTeste['customer_city'][i]).lower()
    dfTeste['customer_state'][i] = str(dfTeste['customer_state'][i]).lower()

C:\Users\leopa\AppData\Local\Temp\ipykernel_15424\2426380906.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfTeste['customer_city'][i] = str(dfTeste['customer_city'][i]).lower()
C:\Users\leopa\AppData\Local\Temp\ipykernel_15424\2426380906.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfTeste['customer_state'][i] = str(dfTeste['customer_state'][i]).lower()

In [35]:
# Transformação de valores

# Transformando numeros
dfTeste['customer_zip_code_prefix'] = pd.to_numeric(dfTeste['customer_zip_code_prefix'], errors = 'coerce')
dfTeste['order_item_id'] = pd.to_numeric(dfTeste['order_item_id'], errors = 'coerce')
dfTeste['price'] = pd.to_numeric(dfTeste['price'], errors = 'coerce')
dfTeste['freight_value'] = pd.to_numeric(dfTeste['freight_value'], errors = 'coerce')
dfTeste['payment_sequential'] = pd.to_numeric(dfTeste['payment_sequential'], errors = 'coerce')
dfTeste['payment_installments'] = pd.to_numeric(dfTeste['payment_installments'], errors = 'coerce')
dfTeste['payment_value'] = pd.to_numeric(dfTeste['payment_value'], errors = 'coerce')
dfTeste['product_name_lenght'] = pd.to_numeric(dfTeste['product_name_lenght'], errors = 'coerce')
dfTeste['product_description_lenght'] = pd.to_numeric(dfTeste['product_description_lenght'], errors = 'coerce')
dfTeste['product_photos_qty'] = pd.to_numeric(dfTeste['product_photos_qty'], errors = 'coerce')
dfTeste['product_weight_g'] = pd.to_numeric(dfTeste['product_weight_g'], errors = 'coerce')
dfTeste['product_length_cm'] = pd.to_numeric(dfTeste['product_length_cm'], errors = 'coerce')
dfTeste['product_height_cm'] = pd.to_numeric(dfTeste['product_height_cm'], errors = 'coerce')
dfTeste['product_width_cm'] = pd.to_numeric(dfTeste['product_width_cm'], errors = 'coerce')
dfTeste['seller_zip_code_prefix'] = pd.to_numeric(dfTeste['seller_zip_code_prefix'], errors = 'coerce')

# Transformando as colunas de data para o tipo datetime
dfTeste['shipping_limit_date'] = pd.to_datetime(dfTeste['shipping_limit_date'], errors='coerce')
dfTeste['order_purchase_timestamp'] = pd.to_datetime(dfTeste['order_purchase_timestamp'], errors='coerce')
dfTeste['order_approved_at'] = pd.to_datetime(dfTeste['order_approved_at'], errors='coerce')

In [36]:
# Tratando valores nulos
for coluna in dfTeste.columns:
    if (str(dfTeste[coluna].dtypes)) == 'float64' or (str(dfTeste[coluna].dtypes)) == 'int64':
        dfTeste[coluna].fillna(dfTeste[coluna].mean(), inplace = True)
    elif dfTeste[coluna].dtype == 'datetime64[ns]':
        dfTeste[coluna].fillna(pd.NaT, inplace=True)
    else:
        dfTeste[coluna].fillna("Ausente", inplace = True)

C:\Users\leopa\AppData\Local\Temp\ipykernel_15424\302684681.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dfTeste[coluna].fillna("Ausente", inplace = True)
C:\Users\leopa\AppData\Local\Temp\ipykernel_15424\302684681.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dfTeste[coluna].fillna(pd.NaT, inplace=True)
C:\Users\leopa\AppData\Local\Temp\ipykernel_15424\302684681.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dfTeste[coluna].fillna(dfTeste[coluna].mean(), inplace = True)

In [37]:
# Transformando em categoricas
dfTeste['product_category_name'] = dfTeste['product_category_name'].astype('category')
dfTeste['payment_type'] = dfTeste['payment_type'].astype('category')
dfTeste['customer_city'] = dfTeste['customer_city'].astype('category')
dfTeste['customer_state'] = dfTeste['customer_state'].astype('category')
dfTeste['seller_city'] = dfTeste['seller_city'].astype('category')
dfTeste['seller_state'] = dfTeste['seller_state'].astype('category')

In [38]:
# Identificador de outliers
def drop_outliers(base, variavel):
    outliers = []
    # Calcula Q1 (25º percentil) para a variável dada
    Q1 = np.percentile(base[variavel], 25)
    
    # Calcula Q3 (75º percentil) para a variável dada
    Q3 = np.percentile(base[variavel], 75)
    
    # Usa IQR (interquartile range) para calcular um passo de outlier
    IQR = Q3-Q1
    passo = 1.5 * IQR
    
    feature_outliers = base[~((base[variavel] >= Q1 - passo) & (base[variavel] <= Q3 + passo))]
    outliers.extend(list(feature_outliers.index.values))
    
    return outliers

In [39]:
# Retirando todos os outliers dos valores numericos

for coluna in dfTeste.columns:
    if (str(dfTeste[coluna].dtypes)) == 'float64' or (str(dfTeste[coluna].dtypes)) == 'int64':
        outliers = drop_outliers(dfTeste, str(coluna))
        dfTesteSemOutliers = dfTeste.drop(dfTeste.index[outliers]).reset_index(drop = True)

dfTeste = dfTesteSemOutliers

In [40]:
dfTeste

,order_id,customer_id,order_purchase_timestamp,order_approved_at,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,payment_sequential,payment_type,payment_installments,payment_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state
0,cee3292f46ede6ea1dfabfcb200fcf47,0f8feee05f830b2be5955cf674a7d8f1,2018-06-21 15:00:00,2018-06-21 17:18:00,04d1643d1bf6c54f0b099c708e623466,8280,são paulo,sao paulo,1,1bfb290d7273a442c874dbe74b4abae6,7c67e1448b00f6e969d365cea6b010ab,2018-07-05 17:18:41,69.99,23.20,1,boleto,1,186.38,moveis_escritorio,19.0,883.0,1.0,10075.0,55.0,64.0,26.0,8577,itaquaquecetuba,SP
1,cee3292f46ede6ea1dfabfcb200fcf47,0f8feee05f830b2be5955cf674a7d8f1,2018-06-21 15:00:00,2018-06-21 17:18:00,04d1643d1bf6c54f0b099c708e623466,8280,são paulo,sao paulo,2,1bfb290d7273a442c874dbe74b4abae6,7c67e1448b00f6e969d365cea6b010ab,2018-07-05 17:18:41,69.99,23.20,1,boleto,1,186.38,moveis_escritorio,19.0,883.0,1.0,10075.0,55.0,64.0,26.0,8577,itaquaquecetuba,SP
2,50dca53ca33b739bef09e7933e8b380e,d0580aed7f303a707d93b00b84c591a7,2018-07-14 09:47:00,2018-07-14 10:04:00,83f6b0c43f9281884da6fb400b587207,7151,guarulhos,sao paulo,1,eb048e296b8db6cd64b1bafd9500786c,1900267e848ceeba8fa32d80c1a5f5a8,2018-07-17 10:04:14,19.90,12.80,1,credit_card,3,65.40,cama_mesa_banho,52.0,149.0,1.0,250.0,16.0,10.0,16.0,14940,ibitinga,SP
3,50dca53ca33b739bef09e7933e8b380e,d0580aed7f303a707d93b00b84c591a7,2018-07-14 09:47:00,2018-07-14 10:04:00,83f6b0c43f9281884da6fb400b587207,7151,guarulhos,sao paulo,2,113f80f12c8892f0c59206f70b862b40,1900267e848ceeba8fa32d80c1a5f5a8,2018-07-17 10:04:14,19.90,12.80,1,credit_card,3,65.40,cama_mesa_banho,52.0,170.0,1.0,250.0,16.0,10.0,16.0,14940,ibitinga,SP
4,8087ec71e393d4dc6fc48041fe63cd51,b8dfb418e6cad762b91febf827d4b2e5,2018-05-14 10:03:00,2018-05-14 10:15:00,ae85516c85361785d9151930418af0cb,4013,sao paulo,sao paulo,1,39cdb64dad488a6037d828d1cd514255,8f119a0aee85c0c8fc534629734e94fd,2018-05-18 10:15:20,22.50,8.64,1,credit_card,3,179.68,casa_construcao,60.0,890.0,2.0,300.0,28.0,9.0,18.0,6440,barueri,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28112,25bd2ad9d282f59e4e6a048ef9bf214f,be34bf56044c5614fc66d97251c0adc6,2018-03-12 16:20:00,2018-03-12 17:09:00,768e9ed92dd4fe880672c8e90dc4f74c,66610,belem,para,1,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-03-16 17:09:53,53.90,42.44,1,credit_card,2,289.02,ferramentas_jardim,57.0,366.0,2.0,1650.0,30.0,22.0,30.0,15025,sao jose do rio preto,SP
28113,25bd2ad9d282f59e4e6a048ef9bf214f,be34bf56044c5614fc66d97251c0adc6,2018-03-12 16:20:00,2018-03-12 17:09:00,768e9ed92dd4fe880672c8e90dc4f74c,66610,belem,para,2,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-03-16 17:09:53,53.90,42.44,1,credit_card,2,289.02,ferramentas_jardim,57.0,366.0,2.0,1650.0,30.0,22.0,30.0,15025,sao jose do rio preto,SP
28114,25bd2ad9d282f59e4e6a048ef9bf214f,be34bf56044c5614fc66d97251c0adc6,2018-03-12 16:20:00,2018-03-12 17:09:00,768e9ed92dd4fe880672c8e90dc4f74c,66610,belem,para,3,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-03-16 17:09:53,53.90,42.44,1,credit_card,2,289.02,ferramentas_jardim,57.0,366.0,2.0,1650.0,30.0,22.0,30.0,15025,sao jose do rio preto,SP
28115,9f9ac312604229686c04260955495c70,3357c4c3ecf82709236158cb2ac0ce9b,2018-05-24 11:38:00,2018-05-24 11:53:00,bc13219ef5b1a254d34e3e6112303dfd,3315,são paulo,sao paulo,1,bb50f2e236e5eea0100680137654686c,f7ba60f8c3f99e7ee4042fdef03b70c4,2018-05-28 11:53:34,330.00,10.07,1,credit_card,8,340.07,beleza_saude,60.0,2644.0,6.0,400.0,34.0,4.0,22.0,9628,sao bernardo do campo,SP
28116,f51c9940410ef77422e4efbca407c161,ceeaae7ee13b40a086d0140281bef2ac,2018-08-16 11:05:00,2018-08-17 03:30:00,d9f2c7c53b2b8071bc518513a8c7a735,85301,laranjeiras do sul,parana,1,020a80cb704bf65f38761fcedf2af192,ef2fbc2b607d8492bcffe657a4645434,2018-08-22 03:30:17,49.90,19.54,1,boleto,1,69.44,automotivo,35.0,1512.0,3.0,800.0,26.0,9.0,24.0,20051,rio de janeiro,RJ

In [41]:
dfTeste.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28117 entries, 0 to 28116
Data columns (total 29 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   order_id                    28117 non-null  object
 1   customer_id                 28117 non-null  object
 2   order_purchase_timestamp    28117 non-null  datetime64[ns]
 3   order_approved_at           28117 non-null  datetime64[ns]
 4   customer_unique_id          28117 non-null  object
 5   customer_zip_code_prefix    28117 non-null  int64
 6   customer_city               28117 non-null  category
 7   customer_state              28117 non-null  category
 8   order_item_id               28117 non-null  int64
 9   product_id                  28117 non-null  object
 10  seller_id                   28117 non-null  object
 11  shipping_limit_date         28117 non-null  datetime64[ns]
 12  price                       28117 non-null  float64
 13  freight_value               28117 non-null  float64
 14  payment_sequential          28117 non-null  int64
 15  payment_type                28117 non-null  category
 16  payment_installments        28117 non-null  int64
 17  payment_value               28117 non-null  float64
 18  product_category_name       28117 non-null  category
 19  product_name_lenght         28117 non-null  float64
 20  product_description_lenght  28117 non-null  float64
 21  product_photos_qty          28117 non-null  float64
 22  product_weight_g            28117 non-null  float64
 23  product_length_cm           28117 non-null  float64
 24  product_height_cm           28117 non-null  float64
 25  product_width_cm            28117 non-null  float64
 26  seller_zip_code_prefix      28117 non-null  int64
 27  seller_city                 28117 non-null  category
 28  seller_state                28117 non-null  category
dtypes: category(6), datetime64[ns](3), float64(10), int64(5), object(5)
memory usage: 5.3+ MB

In [43]:
# Exportando tudo para um excel
dfTeste.to_excel('./baseDeDados/dataBaseTeste.xlsx', sheet_name='dadosTeste', index=False)